### ISSUE TITLE
Can't find "useFftw.h" when compiling test_acquisition_check

### ISSUE THREAD

**Issue by Algafix** [cisagov/PNT-Integrity#1]
# 🐛 Summary #

When compiling the PNT-Integrity with BUILD_PNT_INTEGRITY_EXAMPLES flag the compiler can't find "useFftw.h" on testAcquisitionCheck.cpp:43:10.

## To reproduce ##

1. mkdir build && cd build
2. cmake ../ -D BUILD_PNT_INTEGRITY_EXAMPLES=ON
3. make

## Expected behavior ##

The examples (repoTestApp and testAcquisitionCheck) should be compiled.

## Any helpful log output or screenshots ##

```console
Scanning dependencies of target test_acquisition_check
[ 91%] Building CXX object pnt_integrity/pnt_integrity/CMakeFiles/test_acquisition_check.dir/examples/testAcquisitionCheck.cpp.o
[redacted]/PNT-Integrity/pnt_integrity/pnt_integrity/examples/testAcquisitionCheck.cpp:43:10: fatal error: useFftw.h: No such file or directory
   43 | #include "useFftw.h"
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [pnt_integrity/pnt_integrity/CMakeFiles/test_acquisition_check.dir/build.make:82: pnt_integrity/pnt_integrity/CMakeFiles/test_acquisition_check.dir/examples/testAcquisitionCheck.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:302: pnt_integrity/pnt_integrity/CMakeFiles/test_acquisition_check.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

## Proposed solution

Include the "useFftw.h" header file in the github repo.

## Workaround

On the file `pnt_integrity/pnt_integrity/examples/testAcquisitionCheck.cpp`.

Replace the `#include "useFftw.h"` statement with `#include <fftw3.h>`.

Then remove the check to use fftw between lines 59 and 65 of the same file, I'm assuming USE_FFTW was defined in useFftw.h:

```
#if (USE_FFTW == 0)
    printLogToStdOut(
        "FFTW package not installed. Cannot use the AcquisitionCheck",
        LogLevel::Error);
    return 0;
#endif
```

**Comment by chris5108** [comment]
@Algafix Fix for this issue has been pushed to new branch bugfix/examples_build_fail.  https://github.com/cisagov/PNT-Integrity/tree/bugfix/examples_build_fail

**Comment by Algafix** [comment]
It works now. Thanks!
