### ISSUE TITLE
(Linux) Compiling test_acquisition_check: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by Algafix** [cisagov/PNT-Integrity#2]
# 🐛 Summary #

When compiling `test_acquisition_check` after the workaround on #1, the compiler finds an error with the pthread library.

## To reproduce ##

1. Apply the workaround of #1 or have the correct files.
2. mkdir build && cd build
3. cmake ../ -D BUILD_PNT_INTEGRITY_EXAMPLES=ON
4. make

## Expected behavior ##

The `test_acquisition_check` test should be compiled.

## Any helpful log output or screenshots ##

```console
[ 94%] Linking CXX executable test_acquisition_check
/usr/bin/ld: libpnt_integrity.a(AcquisitionCheck.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [pnt_integrity/pnt_integrity/CMakeFiles/test_acquisition_check.dir/build.make:115: pnt_integrity/pnt_integrity/test_acquisition_check] Error 1
make[1]: *** [CMakeFiles/Makefile2:302: pnt_integrity/pnt_integrity/CMakeFiles/test_acquisition_check.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```
## Workaround

In linux (what i've tested) the libraries need to be specified after the object files being compiled.

Therefore, in `pnt_integrity/pnt_integrity/CMakeLists.txt`, on line 149 add:

```
# Threads linux
set(CMAKE_THREAD_LIBS_INIT "-lpthread")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
```

#### Note

After all, when the `test_acquisition_check` is executed it looks for the file `if_data.bin` that doesn't exist and for which I do not know the format.

**Comment by chris5108** [comment]
@Algafix Fix for this issue has been pushed to new branch bugfix/examples_build_fail. https://github.com/cisagov/PNT-Integrity/tree/bugfix/examples_build_fail

**Comment by Algafix** [comment]
It works now, thanks!
